services:
    db:
        image: mysql:8.0
        container_name: sumo_db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sumo
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
#        networks:
#            - laravel-network
volumes:
    db_data:
#networks:
#    laravel-network:
#        driver: bridge
